// Risk Analysis Types for the Risk Dashboard
// Based on the 42 xlsx files generated by risk.py

/**
 * Risk analysis mode: Exposure → Vulnerability → Damage
 */
export type RiskMode = 'Exp' | 'Vul' | 'Dmg' | 'Pop';

/**
 * All 16 asset keys from the xlsx columns B-Q
 */
export type RiskAssetKey =
  | 'crop'           // Cropped Area (ha)
  | 'buildLow56'     // Buildings <3m (56%) (sq.m)
  | 'buildLow44'     // Buildings <3m (44%) (sq.m)
  | 'buildHigh'      // Buildings >=3m (sq.m)
  | 'telecom'        // Telecom Tower
  | 'electric'       // Electric lines
  | 'railways'       // Railways
  | 'hospitals'      // Hospitals
  | 'bhu'            // BHU
  | 'schools'        // Schools
  | 'roads'          // Roads
  | 'embankments'    // Embankments
  | 'mainCanals'     // Main Canals
  | 'branchCanals'   // Branch Canals
  | 'drains'         // Drains
  | 'livestock';     // Livestock

export const RISK_ASSET_LABELS: Record<RiskAssetKey, string> = {
  crop: 'Cropped Area (ha)',
  buildLow56: 'Buildings <3m (56%)',
  buildLow44: 'Buildings <3m (44%)',
  buildHigh: 'Buildings ≥3m',
  telecom: 'Telecom Tower',
  electric: 'Electric Lines',
  railways: 'Railways',
  hospitals: 'Hospitals',
  bhu: 'BHU',
  schools: 'Schools',
  roads: 'Roads',
  embankments: 'Embankments',
  mainCanals: 'Main Canals',
  branchCanals: 'Branch Canals',
  drains: 'Drains',
  livestock: 'Livestock',
};

export const RISK_ASSET_SHORT_LABELS: Record<RiskAssetKey, string> = {
  crop: 'Crops',
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
  telecom: 'Telecom',
  electric: 'Electric',
  railways: 'Railways',
  hospitals: 'Hospitals',
  bhu: 'BHU',
  schools: 'Schools',
  roads: 'Roads',
  embankments: 'Embankments',
  mainCanals: 'Main Canals',
  branchCanals: 'Branch Canals',
  drains: 'Drains',
  livestock: 'Livestock',
};

export const RISK_ASSET_COLORS: Record<RiskAssetKey, string> = {
  crop: '#22c55e',
  buildLow56: '#93c5fd',
  buildLow44: '#3b82f6',
  buildHigh: '#1e3a8a',
  telecom: '#a855f7',
  electric: '#f59e0b',
  railways: '#ef4444',
  hospitals: '#ec4899',
  bhu: '#06b6d4',
  schools: '#8b5cf6',
  roads: '#64748b',
  embankments: '#14b8a6',
  mainCanals: '#0ea5e9',
  branchCanals: '#38bdf8',
  drains: '#0284c7',
  livestock: '#f97316',
};

/** All 16 asset keys in order */
export const RISK_ASSET_KEYS: RiskAssetKey[] = [
  'crop', 'buildLow56', 'buildLow44', 'buildHigh',
  'telecom', 'electric', 'railways',
  'hospitals', 'bhu', 'schools', 'roads',
  'embankments', 'mainCanals', 'branchCanals', 'drains', 'livestock',
];

/** Legacy types for compatibility */
export type RiskAssetType = 'crop' | 'buildings';
export type BuildingSubKey = 'buildLow56' | 'buildLow44' | 'buildHigh';

export const BUILDING_SUB_LABELS: Record<BuildingSubKey, string> = {
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
};

export const BUILDING_SUB_COLORS: Record<BuildingSubKey, string> = {
  buildLow56: '#93c5fd',
  buildLow44: '#3b82f6',
  buildHigh: '#1e3a8a',
};

export const BUILDING_KEYS: BuildingSubKey[] = ['buildLow56', 'buildLow44', 'buildHigh'];

/** Legacy type for backward compatibility - use RiskAssetKey for new code */
export type RiskAssetType = 'crop' | 'buildings';

export function buildingsTotal(d: RegionRiskData): number {
  return d.buildLow56 + d.buildLow44 + d.buildHigh;
}

/** Sum of infrastructure assets (telecom, electric, railways, roads) */
export function infrastructureTotal(d: RegionRiskData): number {
  return d.telecom + d.electric + d.railways + d.roads;
}

/** Sum of critical facilities (hospitals, bhu, schools) */
export function facilitiesTotal(d: RegionRiskData): number {
  return d.hospitals + d.bhu + d.schools;
}

export const RISK_MODE_LABELS: Record<RiskMode, string> = {
  Exp: 'Exposure',
  Vul: 'Vulnerability',
  Dmg: 'Economic Damage',
  Pop: 'Population',
};

/**
 * Data for one region in one scenario for one mode
 * Contains all 16 asset types from the Excel files
 */
export type RegionRiskData = {
  crop: number;
  buildLow56: number;
  buildLow44: number;
  buildHigh: number;
  telecom: number;
  electric: number;
  railways: number;
  hospitals: number;
  bhu: number;
  schools: number;
  roads: number;
  embankments: number;
  mainCanals: number;
  branchCanals: number;
  drains: number;
  livestock: number;
};

export function totalRiskValue(data: RegionRiskData): number {
  return Object.values(data).reduce((sum, val) => sum + val, 0);
}

/**
 * Scenario key format: "25_present_perfect"
 */
export type ScenarioKey = string;

export type ScenarioMeta = {
  returnPeriod: number;
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
};

export type RiskJsonData = {
  generated: string;
  scenarios: Record<ScenarioKey, ScenarioMeta>;
  data: Record<ScenarioKey, Record<string, Record<RiskMode, RegionRiskData>>>;
  districts: string[];
};

export type RiskView = 'summary' | 'district' | 'spatial' | 'ead' | 'eal' | 'population' | 'hotspots';

/**
 * 7 districts in Sindh Province (Naushahro Feroze and Shaheed Benazirabad excluded)
 */
export const DISTRICTS = [
  'Dadu',
  'Jacobabad',
  'Jamshoro',
  'Kashmore',
  'Larkana',
  'Qambar Shahdadkot',
  'Shikarpur',
] as const;

export type DistrictName = (typeof DISTRICTS)[number];

/**
 * Return periods in order
 */
export const RETURN_PERIODS = [2.3, 5, 10, 25, 50, 100, 500] as const;

/**
 * Maintenance levels
 */
export const MAINTENANCE_LEVELS = ['perfect', 'breaches', 'redcapacity'] as const;

export const MAINTENANCE_LABELS: Record<string, string> = {
  perfect: 'Perfect',
  breaches: 'Breaches',
  redcapacity: 'Reduced Capacity',
};

/**
 * Sequential color scale for risk values (yellow → red)
 */
export const RISK_COLORS = [
  '#ffffcc', // very low
  '#ffeda0',
  '#fed976',
  '#feb24c',
  '#fd8d3c',
  '#fc4e2a',
  '#e31a1c', // extreme
] as const;

/**
 * Get color from sequential scale based on normalized value (0-1)
 */
export function getRiskColor(value: number, min: number, max: number): string {
  if (max === min) return RISK_COLORS[0];
  const normalized = (value - min) / (max - min);
  const idx = Math.min(Math.floor(normalized * RISK_COLORS.length), RISK_COLORS.length - 1);
  return RISK_COLORS[Math.max(0, idx)];
}

/**
 * Format a large number for display
 * e.g., 1234567 → "$1.23M", 456 → "456", 1234567890 → "$1.23B"
 */
export function formatRiskValue(value: number, mode: RiskMode): string {
  if (value === 0) return '0';

  if (mode === 'Dmg') {
    // Monetary values
    if (value >= 1e9) return `$${(value / 1e9).toFixed(1)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(1)}M`;
    if (value >= 1e3) return `$${(value / 1e3).toFixed(0)}K`;
    return `$${value.toFixed(0)}`;
  }

  // Area/count/population values
  if (value >= 1e9) return `${(value / 1e9).toFixed(1)}B`;
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(0)}K`;
  return value.toFixed(0);
}

/**
 * Format value with full precision for tooltips and tables
 */
export function formatRiskValueFull(value: number, mode: RiskMode): string {
  if (value === 0) return mode === 'Dmg' ? '$0' : '0';

  if (mode === 'Dmg') {
    if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(1)}M`;
    if (value >= 1e3) return `$${(value / 1e3).toFixed(0)}K`;
    return `$${value.toFixed(0)}`;
  }

  if (mode === 'Pop') {
    return Math.round(value).toLocaleString();
  }

  if (value >= 1e9) return `${(value / 1e9).toFixed(2)}B`;
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(0)}K`;
  return value.toFixed(0);
}

/**
 * Get unit label for a mode
 */
export function getRiskUnitLabel(mode: RiskMode): string {
  switch (mode) {
    case 'Exp': return 'Area (ha / sqm)';
    case 'Vul': return 'Vulnerable Area (ha / sqm)';
    case 'Dmg': return 'Economic Damage (USD)';
    case 'Pop': return 'Estimated Fatalities';
  }
}

/**
 * Build scenario key from components
 */
export function buildScenarioKey(
  returnPeriod: number,
  climate: 'present' | 'future',
  maintenance: 'breaches' | 'redcapacity' | 'perfect'
): ScenarioKey {
  return `${returnPeriod}_${climate}_${maintenance}`;
}

// ---- Loss Estimation (Loss/Damage factors) ----

/**
 * Sectors with their Derived Factor (Loss/Damage ratio).
 * Per-asset loss = damage × factor of the sector the asset belongs to.
 *
 * Note: WASH has no matching asset in the 16-asset model and contributes 0.
 */
export type SectorKey =
  | 'agriculture'
  | 'commerce'
  | 'water'
  | 'energy'
  | 'transport'
  | 'housing'
  | 'education'
  | 'health'
  | 'wash';

export const SECTOR_FACTORS: Record<SectorKey, number> = {
  agriculture: 2.51, // Agriculture, Food, Livestock
  commerce: 18.95,   // Commerce & Industries
  water: 0.21,       // Water Resources & Irrigation
  energy: 0.36,      // Energy
  transport: 0.02,   // Transport & Communications
  housing: 0.11,     // Housing / Settlements
  education: 0.39,   // Education
  health: 0.30,      // Health
  wash: 0.64,        // WASH (Water & Sanitation) — no asset, contributes 0
};

export const SECTOR_LABELS: Record<SectorKey, string> = {
  agriculture: 'Agriculture, Food, Livestock',
  commerce: 'Commerce & Industries',
  water: 'Water Resources & Irrigation',
  energy: 'Energy',
  transport: 'Transport & Communications',
  housing: 'Housing / Settlements',
  education: 'Education',
  health: 'Health',
  wash: 'WASH (Water & Sanitation)',
};

export const SECTOR_COLORS: Record<SectorKey, string> = {
  agriculture: '#22c55e',
  commerce: '#f59e0b',
  water: '#06b6d4',
  energy: '#eab308',
  transport: '#64748b',
  housing: '#3b82f6',
  education: '#8b5cf6',
  health: '#ec4899',
  wash: '#14b8a6',
};

export const SECTOR_ICONS: Record<SectorKey, string> = {
  agriculture: '🌾',
  commerce: '🏭',
  water: '🌊',
  energy: '⚡',
  transport: '🛣️',
  housing: '🏠',
  education: '🎓',
  health: '🏥',
  wash: '🚰',
};

/** All sectors in display order */
export const SECTOR_KEYS: SectorKey[] = [
  'agriculture', 'commerce', 'water', 'energy', 'transport',
  'housing', 'education', 'health', 'wash',
];

/** Asset → sector mapping (buildHigh → Commerce per project decision) */
export const ASSET_SECTOR: Record<RiskAssetKey, SectorKey> = {
  crop: 'agriculture',
  livestock: 'agriculture',
  buildHigh: 'commerce',
  embankments: 'water',
  mainCanals: 'water',
  branchCanals: 'water',
  drains: 'water',
  electric: 'energy',
  roads: 'transport',
  railways: 'transport',
  telecom: 'transport',
  buildLow56: 'housing',
  buildLow44: 'housing',
  schools: 'education',
  hospitals: 'health',
  bhu: 'health',
};

/** Sector → its assets (WASH = []) */
export const SECTOR_ASSETS: Record<SectorKey, RiskAssetKey[]> = {
  agriculture: ['crop', 'livestock'],
  commerce: ['buildHigh'],
  water: ['embankments', 'mainCanals', 'branchCanals', 'drains'],
  energy: ['electric'],
  transport: ['roads', 'railways', 'telecom'],
  housing: ['buildLow56', 'buildLow44'],
  education: ['schools'],
  health: ['hospitals', 'bhu'],
  wash: [],
};

/** Asset → its sector's factor (convenience) */
export const ASSET_SECTOR_FACTOR: Record<RiskAssetKey, number> = Object.fromEntries(
  RISK_ASSET_KEYS.map((asset) => [asset, SECTOR_FACTORS[ASSET_SECTOR[asset]]])
) as Record<RiskAssetKey, number>;

// All building types (buildLow56, buildLow44, buildHigh) use the Housing sector
// factor (0.11) per domain review (2026-07). buildLow56/buildLow44 inherit it via
// the housing sector mapping above; buildHigh's nominal sector is Commerce (18.95),
// so it needs an explicit override to match the other buildings.
ASSET_SECTOR_FACTOR.buildHigh = SECTOR_FACTORS.housing; // 0.11

/**
 * Compute per-asset loss from damage: loss[asset] = dmg[asset] × sector factor.
 */
export function computeAssetLoss(dmg: RegionRiskData): RegionRiskData {
  return {
    crop: dmg.crop * ASSET_SECTOR_FACTOR.crop,
    buildLow56: dmg.buildLow56 * ASSET_SECTOR_FACTOR.buildLow56,
    buildLow44: dmg.buildLow44 * ASSET_SECTOR_FACTOR.buildLow44,
    buildHigh: dmg.buildHigh * ASSET_SECTOR_FACTOR.buildHigh,
    telecom: dmg.telecom * ASSET_SECTOR_FACTOR.telecom,
    electric: dmg.electric * ASSET_SECTOR_FACTOR.electric,
    railways: dmg.railways * ASSET_SECTOR_FACTOR.railways,
    hospitals: dmg.hospitals * ASSET_SECTOR_FACTOR.hospitals,
    bhu: dmg.bhu * ASSET_SECTOR_FACTOR.bhu,
    schools: dmg.schools * ASSET_SECTOR_FACTOR.schools,
    roads: dmg.roads * ASSET_SECTOR_FACTOR.roads,
    embankments: dmg.embankments * ASSET_SECTOR_FACTOR.embankments,
    mainCanals: dmg.mainCanals * ASSET_SECTOR_FACTOR.mainCanals,
    branchCanals: dmg.branchCanals * ASSET_SECTOR_FACTOR.branchCanals,
    drains: dmg.drains * ASSET_SECTOR_FACTOR.drains,
    livestock: dmg.livestock * ASSET_SECTOR_FACTOR.livestock,
  };
}

/**
 * Build a parallel dataset where every `Dmg` block is replaced by its loss.
 * Exp/Vul are untouched. Used by per-scenario views when the Loss toggle is on.
 */
export function toLossData(data: RiskJsonData): RiskJsonData {
  const lossData: RiskJsonData = {
    generated: data.generated,
    scenarios: data.scenarios,
    districts: data.districts,
    data: {},
  };
  for (const scenarioKey of Object.keys(data.data)) {
    lossData.data[scenarioKey] = {};
    for (const region of Object.keys(data.data[scenarioKey])) {
      const regionModes = data.data[scenarioKey][region];
      lossData.data[scenarioKey][region] = {
        Exp: regionModes.Exp,
        Vul: regionModes.Vul,
        Dmg: regionModes.Dmg ? computeAssetLoss(regionModes.Dmg) : regionModes.Dmg,
      };
    }
  }
  return lossData;
}

// ---- EAD (Expected Annual Damage) ----

/** Asset keys for EAD computation - now includes all 16 assets */
export type AssetSubKey = RiskAssetKey;

/** All 16 asset keys in display order for EAD */
export const ASSET_SUB_KEYS: AssetSubKey[] = [
  'crop', 'buildLow56', 'buildLow44', 'buildHigh',
  'telecom', 'electric', 'railways',
  'hospitals', 'bhu', 'schools', 'roads',
  'embankments', 'mainCanals', 'branchCanals', 'drains', 'livestock',
];

/** Assets to display in UI */
export const DISPLAY_ASSET_KEYS: AssetSubKey[] = [
  'crop', 'buildLow56', 'buildLow44', 'buildHigh',
  'telecom', 'electric', 'railways',
  'hospitals', 'bhu', 'schools', 'roads',
  'embankments', 'mainCanals', 'branchCanals', 'drains', 'livestock',
];

/** Human-readable labels for each asset sub-key */
export const ASSET_SUB_KEY_LABELS: Record<AssetSubKey, string> = {
  crop: 'Agriculture',
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
  telecom: 'Telecom',
  electric: 'Electric',
  railways: 'Railways',
  hospitals: 'Hospitals',
  bhu: 'BHU',
  schools: 'Schools',
  roads: 'Roads',
  embankments: 'Embankments',
  mainCanals: 'Main Canals',
  branchCanals: 'Branch Canals',
  drains: 'Drains',
  livestock: 'Livestock',
};

/** Result of EAD calculation for one climate × maintenance × region */
export type EadResult = {
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
  region: string;
  ead: Record<AssetSubKey, number>;
  eadTotal: number;
};

/** Result of Expected Annual Loss (EAL) calculation for one climate × maintenance × region */
export type EalResult = {
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
  region: string;
  eal: Record<AssetSubKey, number>;
  ealTotal: number;
};

/** Result of Expected Annual Population Affected (EAPA) calculation */
export type EapaResult = {
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
  region: string;
  eapa: number;
  byDistrict?: Record<DistrictName, number>;
};

/**
 * Calculate Expected Annual Damage using trapezoidal integration.
 *
 * EAD = Σ 0.5 × (Dᵢ + Dᵢ₊₁) × |1/RPᵢ - 1/RPᵢ₊₁|
 *
 * @param damages - Array of { returnPeriod, damage } sorted by returnPeriod ascending
 */
export function calculateEad(damages: { returnPeriod: number; damage: number }[]): number {
  if (damages.length < 2) return 0;
  let ead = 0;
  for (let i = 0; i < damages.length - 1; i++) {
    const freqLeft = 1 / damages[i].returnPeriod;
    const freqRight = 1 / damages[i + 1].returnPeriod;
    ead += 0.5 * (damages[i].damage + damages[i + 1].damage) * Math.abs(freqLeft - freqRight);
  }
  return ead;
}

/**
 * Calculate TOTAL risk data by summing all districts for a given scenario and mode.
 * This ensures TOTAL reflects only the active districts (7, not 9).
 */
export function calculateTotalRisk(
  data: RiskJsonData,
  scenarioKey: ScenarioKey,
  mode: RiskMode
): RegionRiskData | null {
  const scenarioData = data.data[scenarioKey];
  if (!scenarioData) return null;

  // Sum all districts for all 16 assets
  const total: RegionRiskData = {
    crop: 0,
    buildLow56: 0,
    buildLow44: 0,
    buildHigh: 0,
    telecom: 0,
    electric: 0,
    railways: 0,
    hospitals: 0,
    bhu: 0,
    schools: 0,
    roads: 0,
    embankments: 0,
    mainCanals: 0,
    branchCanals: 0,
    drains: 0,
    livestock: 0,
  };

  for (const district of DISTRICTS) {
    const districtData = scenarioData[district]?.[mode];
    if (!districtData) continue;

    total.crop += districtData.crop ?? 0;
    total.buildLow56 += districtData.buildLow56 ?? 0;
    total.buildLow44 += districtData.buildLow44 ?? 0;
    total.buildHigh += districtData.buildHigh ?? 0;
    total.telecom += districtData.telecom ?? 0;
    total.electric += districtData.electric ?? 0;
    total.railways += districtData.railways ?? 0;
    total.hospitals += districtData.hospitals ?? 0;
    total.bhu += districtData.bhu ?? 0;
    total.schools += districtData.schools ?? 0;
    total.roads += districtData.roads ?? 0;
    total.embankments += districtData.embankments ?? 0;
    total.mainCanals += districtData.mainCanals ?? 0;
    total.branchCanals += districtData.branchCanals ?? 0;
    total.drains += districtData.drains ?? 0;
    total.livestock += districtData.livestock ?? 0;
  }

  return total;
}
