// Risk Analysis Types for the Risk Dashboard
// Based on the 42 xlsx files generated by risk.py

/**
 * Risk analysis mode: Exposure → Vulnerability → Damage
 */
export type RiskMode = 'Exp' | 'Vul' | 'Dmg' | 'Pop';

/**
 * All 11 asset keys from the xlsx columns B-L
 */
export type RiskAssetKey =
  | 'crop'           // Cropped Area (ha)
  | 'buildLow56'     // Buildings <3m (56%) (sq.m)
  | 'buildLow44'     // Buildings <3m (44%) (sq.m)
  | 'buildHigh'      // Buildings >=3m (sq.m)
  | 'telecom'        // Telecom Tower
  | 'electric'       // Electric lines
  | 'railways'       // Railways
  | 'hospitals'      // Hospitals
  | 'bhu'            // BHU
  | 'schools'        // Schools
  | 'roads';         // Roads

export const RISK_ASSET_LABELS: Record<RiskAssetKey, string> = {
  crop: 'Cropped Area (ha)',
  buildLow56: 'Buildings <3m (56%)',
  buildLow44: 'Buildings <3m (44%)',
  buildHigh: 'Buildings ≥3m',
  telecom: 'Telecom Tower',
  electric: 'Electric Lines',
  railways: 'Railways',
  hospitals: 'Hospitals',
  bhu: 'BHU',
  schools: 'Schools',
  roads: 'Roads',
};

export const RISK_ASSET_SHORT_LABELS: Record<RiskAssetKey, string> = {
  crop: 'Crops',
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
  telecom: 'Telecom',
  electric: 'Electric',
  railways: 'Railways',
  hospitals: 'Hospitals',
  bhu: 'BHU',
  schools: 'Schools',
  roads: 'Roads',
};

export const RISK_ASSET_COLORS: Record<RiskAssetKey, string> = {
  crop: '#22c55e',
  buildLow56: '#93c5fd',
  buildLow44: '#3b82f6',
  buildHigh: '#1e3a8a',
  telecom: '#a855f7',
  electric: '#f59e0b',
  railways: '#ef4444',
  hospitals: '#ec4899',
  bhu: '#06b6d4',
  schools: '#8b5cf6',
  roads: '#64748b',
};

/** All 11 asset keys in order */
export const RISK_ASSET_KEYS: RiskAssetKey[] = [
  'crop', 'buildLow56', 'buildLow44', 'buildHigh',
  'telecom', 'electric', 'railways',
  'hospitals', 'bhu', 'schools', 'roads',
];

/** Legacy types for compatibility */
export type RiskAssetType = 'crop' | 'buildings';
export type BuildingSubKey = 'buildLow56' | 'buildLow44' | 'buildHigh';

export const BUILDING_SUB_LABELS: Record<BuildingSubKey, string> = {
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
};

export const BUILDING_SUB_COLORS: Record<BuildingSubKey, string> = {
  buildLow56: '#93c5fd',
  buildLow44: '#3b82f6',
  buildHigh: '#1e3a8a',
};

export const BUILDING_KEYS: BuildingSubKey[] = ['buildLow56', 'buildLow44', 'buildHigh'];

/** Legacy type for backward compatibility - use RiskAssetKey for new code */
export type RiskAssetType = 'crop' | 'buildings';

export function buildingsTotal(d: RegionRiskData): number {
  return d.buildLow56 + d.buildLow44 + d.buildHigh;
}

/** Sum of infrastructure assets (telecom, electric, railways, roads) */
export function infrastructureTotal(d: RegionRiskData): number {
  return d.telecom + d.electric + d.railways + d.roads;
}

/** Sum of critical facilities (hospitals, bhu, schools) */
export function facilitiesTotal(d: RegionRiskData): number {
  return d.hospitals + d.bhu + d.schools;
}

export const RISK_MODE_LABELS: Record<RiskMode, string> = {
  Exp: 'Exposure',
  Vul: 'Vulnerability',
  Dmg: 'Economic Damage',
  Pop: 'Population',
};

/**
 * Data for one region in one scenario for one mode
 * Contains all 11 asset types from the Excel files
 */
export type RegionRiskData = {
  crop: number;
  buildLow56: number;
  buildLow44: number;
  buildHigh: number;
  telecom: number;
  electric: number;
  railways: number;
  hospitals: number;
  bhu: number;
  schools: number;
  roads: number;
};

export function totalRiskValue(data: RegionRiskData): number {
  return Object.values(data).reduce((sum, val) => sum + val, 0);
}

/**
 * Scenario key format: "25_present_perfect"
 */
export type ScenarioKey = string;

export type ScenarioMeta = {
  returnPeriod: number;
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
};

export type RiskJsonData = {
  generated: string;
  scenarios: Record<ScenarioKey, ScenarioMeta>;
  data: Record<ScenarioKey, Record<string, Record<RiskMode, RegionRiskData>>>;
  districts: string[];
};

export type RiskView = 'summary' | 'district' | 'spatial' | 'ead' | 'population' | 'hotspots';

/**
 * 7 districts in Sindh Province (Naushahro Feroze and Shaheed Benazirabad excluded)
 */
export const DISTRICTS = [
  'Dadu',
  'Jacobabad',
  'Jamshoro',
  'Kashmore',
  'Larkana',
  'Qambar Shahdadkot',
  'Shikarpur',
] as const;

export type DistrictName = (typeof DISTRICTS)[number];

/**
 * Return periods in order
 */
export const RETURN_PERIODS = [2.3, 5, 10, 25, 50, 100, 500] as const;

/**
 * Maintenance levels
 */
export const MAINTENANCE_LEVELS = ['perfect', 'breaches', 'redcapacity'] as const;

export const MAINTENANCE_LABELS: Record<string, string> = {
  perfect: 'Perfect',
  breaches: 'Breaches',
  redcapacity: 'Reduced Capacity',
};

/**
 * Sequential color scale for risk values (yellow → red)
 */
export const RISK_COLORS = [
  '#ffffcc', // very low
  '#ffeda0',
  '#fed976',
  '#feb24c',
  '#fd8d3c',
  '#fc4e2a',
  '#e31a1c', // extreme
] as const;

/**
 * Get color from sequential scale based on normalized value (0-1)
 */
export function getRiskColor(value: number, min: number, max: number): string {
  if (max === min) return RISK_COLORS[0];
  const normalized = (value - min) / (max - min);
  const idx = Math.min(Math.floor(normalized * RISK_COLORS.length), RISK_COLORS.length - 1);
  return RISK_COLORS[Math.max(0, idx)];
}

/**
 * Format a large number for display
 * e.g., 1234567 → "$1.23M", 456 → "456", 1234567890 → "$1.23B"
 */
export function formatRiskValue(value: number, mode: RiskMode): string {
  if (value === 0) return '0';

  if (mode === 'Dmg') {
    // Monetary values
    if (value >= 1e9) return `$${(value / 1e9).toFixed(1)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(1)}M`;
    if (value >= 1e3) return `$${(value / 1e3).toFixed(0)}K`;
    return `$${value.toFixed(0)}`;
  }

  // Area/count/population values
  if (value >= 1e9) return `${(value / 1e9).toFixed(1)}B`;
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(0)}K`;
  return value.toFixed(0);
}

/**
 * Format value with full precision for tooltips and tables
 */
export function formatRiskValueFull(value: number, mode: RiskMode): string {
  if (value === 0) return mode === 'Dmg' ? '$0' : '0';

  if (mode === 'Dmg') {
    if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(1)}M`;
    if (value >= 1e3) return `$${(value / 1e3).toFixed(0)}K`;
    return `$${value.toFixed(0)}`;
  }

  if (mode === 'Pop') {
    return Math.round(value).toLocaleString();
  }

  if (value >= 1e9) return `${(value / 1e9).toFixed(2)}B`;
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(0)}K`;
  return value.toFixed(0);
}

/**
 * Get unit label for a mode
 */
export function getRiskUnitLabel(mode: RiskMode): string {
  switch (mode) {
    case 'Exp': return 'Area (ha / sqm)';
    case 'Vul': return 'Vulnerable Area (ha / sqm)';
    case 'Dmg': return 'Economic Damage (USD)';
    case 'Pop': return 'Estimated Fatalities';
  }
}

/**
 * Build scenario key from components
 */
export function buildScenarioKey(
  returnPeriod: number,
  climate: 'present' | 'future',
  maintenance: 'breaches' | 'redcapacity' | 'perfect'
): ScenarioKey {
  return `${returnPeriod}_${climate}_${maintenance}`;
}

// ---- EAD (Expected Annual Damage) ----

/** Asset keys for EAD computation - now includes all 11 assets */
export type AssetSubKey = RiskAssetKey;

/** All 11 asset keys in display order for EAD */
export const ASSET_SUB_KEYS: AssetSubKey[] = [
  'crop', 'buildLow56', 'buildLow44', 'buildHigh',
  'telecom', 'electric', 'railways',
  'hospitals', 'bhu', 'schools', 'roads',
];

/** Assets to display in UI */
export const DISPLAY_ASSET_KEYS: AssetSubKey[] = [
  'crop', 'buildLow56', 'buildLow44', 'buildHigh',
  'telecom', 'electric', 'railways',
  'hospitals', 'bhu', 'schools', 'roads',
];

/** Human-readable labels for each asset sub-key */
export const ASSET_SUB_KEY_LABELS: Record<AssetSubKey, string> = {
  crop: 'Agriculture',
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
  telecom: 'Telecom',
  electric: 'Electric',
  railways: 'Railways',
  hospitals: 'Hospitals',
  bhu: 'BHU',
  schools: 'Schools',
  roads: 'Roads',
};

/** Result of EAD calculation for one climate × maintenance × region */
export type EadResult = {
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
  region: string;
  ead: Record<AssetSubKey, number>;
  eadTotal: number;
};

/** Result of Expected Annual Population Affected (EAPA) calculation */
export type EapaResult = {
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
  region: string;
  eapa: number;
  byDistrict?: Record<DistrictName, number>;
};

/**
 * Calculate Expected Annual Damage using trapezoidal integration.
 *
 * EAD = Σ 0.5 × (Dᵢ + Dᵢ₊₁) × |1/RPᵢ - 1/RPᵢ₊₁|
 *
 * @param damages - Array of { returnPeriod, damage } sorted by returnPeriod ascending
 */
export function calculateEad(damages: { returnPeriod: number; damage: number }[]): number {
  if (damages.length < 2) return 0;
  let ead = 0;
  for (let i = 0; i < damages.length - 1; i++) {
    const freqLeft = 1 / damages[i].returnPeriod;
    const freqRight = 1 / damages[i + 1].returnPeriod;
    ead += 0.5 * (damages[i].damage + damages[i + 1].damage) * Math.abs(freqLeft - freqRight);
  }
  return ead;
}

/**
 * Calculate TOTAL risk data by summing all districts for a given scenario and mode.
 * This ensures TOTAL reflects only the active districts (7, not 9).
 */
export function calculateTotalRisk(
  data: RiskJsonData,
  scenarioKey: ScenarioKey,
  mode: RiskMode
): RegionRiskData | null {
  const scenarioData = data.data[scenarioKey];
  if (!scenarioData) return null;

  // Sum all districts for all 11 assets
  const total: RegionRiskData = {
    crop: 0,
    buildLow56: 0,
    buildLow44: 0,
    buildHigh: 0,
    telecom: 0,
    electric: 0,
    railways: 0,
    hospitals: 0,
    bhu: 0,
    schools: 0,
    roads: 0,
  };

  for (const district of DISTRICTS) {
    const districtData = scenarioData[district]?.[mode];
    if (!districtData) continue;

    total.crop += districtData.crop ?? 0;
    total.buildLow56 += districtData.buildLow56 ?? 0;
    total.buildLow44 += districtData.buildLow44 ?? 0;
    total.buildHigh += districtData.buildHigh ?? 0;
    total.telecom += districtData.telecom ?? 0;
    total.electric += districtData.electric ?? 0;
    total.railways += districtData.railways ?? 0;
    total.hospitals += districtData.hospitals ?? 0;
    total.bhu += districtData.bhu ?? 0;
    total.schools += districtData.schools ?? 0;
    total.roads += districtData.roads ?? 0;
  }

  return total;
}
