// Risk Analysis Types for the Risk Dashboard
// Based on the 42 xlsx files generated by risk.py

/**
 * Risk analysis mode: Exposure → Vulnerability → Damage
 */
export type RiskMode = 'Exp' | 'Vul' | 'Dmg';

/**
 * Asset types from the xlsx columns
 */
export type RiskAssetType = 'crop' | 'buildLow56' | 'buildLow44' | 'buildHigh';

export const RISK_ASSET_LABELS: Record<RiskAssetType, string> = {
  crop: 'Agriculture Damage (ha)',
  buildLow56: 'Kacha (sqm)',
  buildLow44: 'Pakka (sqm)',
  buildHigh: 'High-Rise (sqm)',
};

export const RISK_ASSET_SHORT_LABELS: Record<RiskAssetType, string> = {
  crop: 'Agriculture',
  buildLow56: 'Kacha',
  buildLow44: 'Pakka',
  buildHigh: 'High-Rise',
};

export const RISK_ASSET_COLORS: Record<RiskAssetType, string> = {
  crop: '#22c55e',
  buildLow56: '#3b82f6',
  buildLow44: '#8b5cf6',
  buildHigh: '#ef4444',
};

export const RISK_MODE_LABELS: Record<RiskMode, string> = {
  Exp: 'Exposure',
  Vul: 'Vulnerability',
  Dmg: 'Economic Damage',
};

/**
 * Data for one region in one scenario for one mode
 */
export type RegionRiskData = {
  crop: number;
  buildLow56: number;
  buildLow44: number;
  buildHigh: number;
};

/**
 * Sum all 4 asset types into a single number
 */
export function totalRiskValue(data: RegionRiskData): number {
  return data.crop + data.buildLow56 + data.buildLow44 + data.buildHigh;
}

/**
 * Scenario key format: "25_present_perfect"
 */
export type ScenarioKey = string;

export type ScenarioMeta = {
  returnPeriod: number;
  climate: 'present' | 'future';
  maintenance: 'breaches' | 'redcapacity' | 'perfect';
};

export type RiskJsonData = {
  generated: string;
  scenarios: Record<ScenarioKey, ScenarioMeta>;
  data: Record<ScenarioKey, Record<string, Record<RiskMode, RegionRiskData>>>;
  districts: string[];
};

export type RiskView = 'summary' | 'district' | 'spatial';

/**
 * 9 districts in Sindh Province
 */
export const DISTRICTS = [
  'Dadu',
  'Jacobabad',
  'Jamshoro',
  'Kashmore',
  'Larkana',
  'Naushahro Feroze',
  'Qambar Shahdadkot',
  'Shaheed Benazirabad',
  'Shikarpur',
] as const;

export type DistrictName = (typeof DISTRICTS)[number];

/**
 * Return periods in order
 */
export const RETURN_PERIODS = [2.3, 5, 10, 25, 50, 100, 500] as const;

/**
 * Maintenance levels
 */
export const MAINTENANCE_LEVELS = ['perfect', 'breaches', 'redcapacity'] as const;

export const MAINTENANCE_LABELS: Record<string, string> = {
  perfect: 'Perfect',
  breaches: 'Breaches',
  redcapacity: 'Reduced Capacity',
};

/**
 * Sequential color scale for risk values (yellow → red)
 */
export const RISK_COLORS = [
  '#ffffcc', // very low
  '#ffeda0',
  '#fed976',
  '#feb24c',
  '#fd8d3c',
  '#fc4e2a',
  '#e31a1c', // extreme
] as const;

/**
 * Get color from sequential scale based on normalized value (0-1)
 */
export function getRiskColor(value: number, min: number, max: number): string {
  if (max === min) return RISK_COLORS[0];
  const normalized = (value - min) / (max - min);
  const idx = Math.min(Math.floor(normalized * RISK_COLORS.length), RISK_COLORS.length - 1);
  return RISK_COLORS[Math.max(0, idx)];
}

/**
 * Format a large number for display
 * e.g., 1234567 → "$1.23M", 456 → "456", 1234567890 → "$1.23B"
 */
export function formatRiskValue(value: number, mode: RiskMode): string {
  if (value === 0) return '0';

  if (mode === 'Dmg') {
    // Monetary values
    if (value >= 1e9) return `$${(value / 1e9).toFixed(1)}B`;
    if (value >= 1e6) return `$${(value / 1e6).toFixed(1)}M`;
    if (value >= 1e3) return `$${(value / 1e3).toFixed(0)}K`;
    return `$${value.toFixed(0)}`;
  }

  // Area/count values
  if (value >= 1e9) return `${(value / 1e9).toFixed(1)}B`;
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(0)}K`;
  return value.toFixed(0);
}

/**
 * Format value with full precision for tooltips
 */
export function formatRiskValueFull(value: number, mode: RiskMode): string {
  if (mode === 'Dmg') {
    return `$${value.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
  }
  return value.toLocaleString(undefined, { maximumFractionDigits: 0 });
}

/**
 * Get unit label for a mode
 */
export function getRiskUnitLabel(mode: RiskMode): string {
  switch (mode) {
    case 'Exp': return 'Area (ha / sqm)';
    case 'Vul': return 'Vulnerable Area (ha / sqm)';
    case 'Dmg': return 'Economic Damage (USD)';
  }
}

/**
 * Build scenario key from components
 */
export function buildScenarioKey(
  returnPeriod: number,
  climate: 'present' | 'future',
  maintenance: 'breaches' | 'redcapacity' | 'perfect'
): ScenarioKey {
  return `${returnPeriod}_${climate}_${maintenance}`;
}
